### ISSUE TITLE
Location of cytoband files for genome browser

### ISSUE THREAD

**Issue by ilarischeinin** [chipster/chipster-tools#1]
The tool `acgh-add-cytobands.R` (in `modules/common/R`) uses the genome browser's annotation files that contain the positions of the cytogenetic bands. It looks like the path to these files has changed, and the tool is therefore giving an error.

At the moment, it looks for the files from the [following path](https://github.com/chipster/chipster-tools/blob/418981921d25117cdc3394be6f2ef3a5423e34ca/modules/common/R/acgh-add-cytobands.R#L18-L19):
`/opt/chipster/tools/genomes/genomebrowser/Homo_sapiens/<genome build>/cytoband-chr.txt`

If you provide me a new location, I can update the tool script.

**Comment by chipster-admin** [comment]
Hello, 

Not sure if someone answered this yet or not, but I think the folder location is the same, but the files are now called <organism>.<genome build>.cytoband-chr.txt 

So for example: 
(chipster.tools.path)/genomes/genomebrowser/Homo_sapiens/GRCh38.83/Homo_sapiens.GRCh38.83.cytoband-chr.txt 

I'm sure Petri or someone will correct me if I'm wrong. 

BR, 
Ari-Matti

**Comment by ilarischeinin** [comment]
Thanks.

A follow up question: since the genome build in the path (and now also in the file name) contains not only the build (above "GRCh38"), but also the version ("83"), can I assume there is only one version present for each build? Or is it possible threre were e.g. both GRCh38.82 and GRCh38.83 directories available?

**Comment by ilarischeinin** [comment]
(Actually, never mind that previous question. I simply made the script able to cope with one or multiple files/directories being present.)

**Comment by klemela** [comment]
Sorry for the slow reply. This far we have had only one version of each build, but it's good that you made it more general. Good to know that also your scripts are using the genome files, so that we can check those when we update the genomes.
